### PR TITLE
Ft summary 2

### PR DESCRIPTION
**Pull request by fentontaylor**
Seasonal summary with the helper methods to build on the group_by framework. Had to add a 2nd argument, 'id' to the methods to look up info for specific team. The `return 0 if games.nil?` line at the beginning of each helper method is because a team doesn't necessarily make the postseason every year, so this way it won't get an error like `undefined method .count for nil::NilClass`. This code runs in about 0.9 seconds and passes the spec harness test.

### CODE REVIEW

**Comment by fentontaylor** [comment]
Results for running rspec on #seasonal_summary. Runs a little faster after now after cleaning it up a bit.
```
> rspec ./spec/stat_tracker_spec.rb:204
Run options: include {:locations=>{"./spec/stat_tracker_spec.rb"=>[204]}}
.
Finished in 0.88498 seconds (files took 0.09985 seconds to load)
1 example, 0 failures
```

**Comment by StarPerfect** [comment]
I don't understand why the ID addition was necessary since on line 3 we have the code pulling out the games that only have the team ID as either the home or away team? So we are never going to look at a game that our team_id team didn't play...

**Comment by fentontaylor** [comment]
On line 3, that is just selecting any game that that team played in, but for calculations, we still need to know if they were the home or away team. If you look at all the helper methods below, they use it to reference home vs. away.

**Comment by StarPerfect** [comment]
Excellent, thank you for the clarification! Great job continuing to work on stuff after we parted ways on Saturday!

**Pull request merged**
