### PR TITLE
Refactor it2 ft

### PR DESCRIPTION
**Pull request by fentontaylor**
Did lots of cleanup:
- Refactored the #from_csv to loop through the data files.
- Refactored GameTest and GameTeamsStats setups to read csv files.

- I noticed that the GameTeamsStats was producing lots of 0s (from nils) so I made sure that the references to the header symbols were in lower case in the GameTeamsStats initialize method.
EXAMPLE: 
     - Actual data header: powerPlayGoals
     - How it was: @power_play_goals = row[:power_play_goals]
     - How it is now: @power_play_goals = row[:powerplaygoals]
-Fixed all the examples similar to above where data headers were camelCase

- Added rounding to the #average_goals_by_season method I wrote earlier.

With these changes. Integrating everything tomorrow should go more smoothly (hopefully!)

### CODE REVIEW

**Comment by StarPerfect** [comment]
so  don't understand why the refactoring was needed on my code. Why wouldnt you have the attr_reader, instance variable AND the row[] name all matching and equal the exact same thing?

**Comment by StarPerfect** [comment]
Not that I'm offended or anything about my code being cleaned up I just don't understand why they wouldn't all be the exact same thing. I thought snake case is how we name stuff, why would you make them all smashed together and lower case?

**Comment by fentontaylor** [comment]
Its because of how the header_converter works. It forces everything to lower case. It's good to have the instance variables in snake_case, but when calling row[:power_play_goals], it returns nil because there is not a header that exactly matches :power_play_goals. The header is actually powerPlayGoals, which gets downcased to powerplaygoals by the header_converter. So let's say the actual value for that row's power play goals is 2. row[:power_play_goals] returns nil, but row[:powerplaygoals] returns 2.

**Comment by fentontaylor** [comment]
I have a feeling that they purposefully gave us messy data to get exposed to dealing with messy real-life data. With real data, you have to spend a ton of time chasing down all the weird irregularities and cleaning them up.

**Comment by StarPerfect** [comment]
And so it was working in my tests because I hard coded the data. I didn't
see that distinction because we weren't testing from the dummy data,
correct?

**Comment by fentontaylor** [comment]
Yeah the tests we wrote passed because they were hard-coded, If just the setup had been changed, then a lot of the assertions failed because there were like 5 or so nils returned. Nancy's way of generating the data for the setup lead to a much more robust test.

**Comment by StarPerfect** [comment]
Naturally! Alright I'll merge the PR if Nancy hasn't by the time I get home
in like 10-15 min.

**Comment by nancylee713** [comment]
I'm home now. I actually encountered the same issue with the lower case thing. So I had to change the naming of the variables to return the expected output.

**Comment by nancylee713** [comment]
Should I merge PR now?

**Comment by fentontaylor** [comment]
Yeah, go ahead.

**Pull request merged**
