### PR TITLE
Module it4 nl

### PR DESCRIPTION
**Pull request by nancylee713**
This module contains 3 methods, including `team_info`, `best_season`, and `worst_season`. All of these methods require a single argument (i.e., `team_id`)

For `best_season`, and `worst_season` methods, a new dummy dataset was created (i.e., dummy_game_3.csv) in order to suit testing, along with 5 helper methods as listed below.

- total_games_per_team
- total_games_per_team_per_season
- total_wins_per_team_per_season
- win_percentage
- win_percentage_per_season

### CODE REVIEW

**Comment by fentontaylor** [comment]
I would be careful about using zip like you did for `win_percentage`. I thought it was a cool idea, so I tried it out in my `postseason_change` but because my hashes were created with a different order of teams, the wrong elements got subtracted from each other. 

```
reg
=> {"6"=>0.75, "5"=>0.42857142857142855, "3"=>0.2}
post
=> {"3"=>0.2, "6"=>0.8888888888888888, "5"=>0.0}
```

It might be better to use .each to make sure you are combining the right values. Here's what I did:

```
reg = percents[:regular_season]
post = percents[:playoff_games]
post.each do |team, percent|
      post[team] = percent - reg[team]
end
post
```
I could have saved the subtractions in a new variable, but I actually only cared about the output of the differences, so I just overwrote the original values to save space.

**Comment by StarPerfect** [comment]
Hey team - I'll be in this morning after an important 9am meeting. Im not sure if I should merge this considering Fenton's comment about using zip so im going to comment and if Navy wants to make changes, go ahead, if Fenton is ok with merging, go ahead.
Great detail in your PR message, Nancy, I think that's excellent! Let me know via Slack if you need me to do anything additional for this PR.

**Comment by nancylee713** [comment]
Thanks for pointing that out Fenton. I'll make changes to `win_percentage` method and make a PR again. Additionally, I've renamed my module and file names to match our team's naming convention.

**Comment by nancylee713** [comment]
I have updated my code now. Since I changed the module name, git does not allow me to push to the same branch anymore. I will close this one and make a new PR.

**Pull request merged**
